# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"NUM_WORKERS": "01_getting_started.ipynb",
         "SAMPLE_RATE": "01_getting_started.ipynb",
         "AudioDataset": "01_getting_started.ipynb",
         "classes": "01_getting_started.ipynb",
         "train_ds": "01_getting_started.ipynb",
         "valid_ds": "01_getting_started.ipynb",
         "audio_to_spec": "01a_spectrogram_dataset.ipynb",
         "SpectrogramDataset": "01a_spectrogram_dataset.ipynb",
         "preds_to_tp_fp_fn": "02_train_on_raw_audio.ipynb",
         "precision": "02_train_on_raw_audio.ipynb",
         "recall": "02_train_on_raw_audio.ipynb",
         "f1": "02_train_on_raw_audio.ipynb"}

modules = ["data.py",
           "metrics.py"]

doc_url = "https://earthspecies.github.io/birdcall/"

git_url = "https://github.com/earthspecies/birdcall/tree/master/"

def custom_doc_links(name): return None
