# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://earthspecies.github.io/birdcall/"

git_url = "https://github.com/earthspecies/birdcall/tree/master/"

def custom_doc_links(name): return None
