# AUTOGENERATED! DO NOT EDIT! File to edit: 02_train_on_raw_audio.ipynb (unless otherwise specified).

__all__ = ['preds_to_tp_fp_fn', 'precision', 'recall', 'f1']

# Cell

def preds_to_tp_fp_fn(preds, targs):
    positives = preds > 0.5
    true_positives = positives[targs == 1]
    false_positives = positives[targs != 1]
    negatives = ~positives
    false_negatives = negatives[targs == 1]
    return true_positives.sum(), false_positives.sum(), false_negatives.sum()

def precision(preds, targs):
    tp, fp, fn = preds_to_tp_fp_fn(preds, targs)
    return (tp.float() / (tp + fp)).item()

def recall(preds, targs):
    tp, fp, fn = preds_to_tp_fp_fn(preds, targs)
    return (tp.float() / (tp + fn)).item()

def f1(preds, targs, eps=1e-8):
    prec = precision(preds, targs)
    rec = recall(preds, targs)
    return 2 * (prec * rec) / (prec + rec + eps)